"""updated tables

Revision ID: 1e14e3ad4046
Revises: ce51e0d27593
Create Date: 2025-08-14 09:41:41.774676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e14e3ad4046'
down_revision: Union[str, None] = 'ce51e0d27593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('udyam_applications', sa.Column('previous_year_itr_filed', sa.Boolean(), nullable=True))
    op.add_column('udyam_applications', sa.Column('has_gstin_status', sa.VARCHAR(length=10), nullable=True))
    op.drop_column('udyam_applications', 'has_gstin')
    op.drop_column('udyam_applications', 'previous_year_itr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('udyam_applications', sa.Column('previous_year_itr', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('udyam_applications', sa.Column('has_gstin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('udyam_applications', 'has_gstin_status')
    op.drop_column('udyam_applications', 'previous_year_itr_filed')
    # ### end Alembic commands ###
