"""create initial tables

Revision ID: ce51e0d27593
Revises: 
Create Date: 2025-08-13 21:40:13.569739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce51e0d27593'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('udyam_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entrepreneur_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('aadhaar_last4', sa.VARCHAR(length=4), nullable=True),
    sa.Column('aadhaar_hash', sa.VARCHAR(length=255), nullable=True),
    sa.Column('aadhaar_consent', sa.Boolean(), nullable=False),
    sa.Column('aadhaar_verified', sa.Boolean(), nullable=False),
    sa.Column('aadhaar_verified_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('pan_masked', sa.VARCHAR(length=20), nullable=True),
    sa.Column('pan_hash', sa.VARCHAR(length=255), nullable=True),
    sa.Column('pan_holder_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('dob_or_doi', sa.DATE(), nullable=True),
    sa.Column('type_of_organisation', sa.VARCHAR(length=50), nullable=True),
    sa.Column('has_gstin', sa.Boolean(), nullable=True),
    sa.Column('previous_year_itr', sa.VARCHAR(length=10), nullable=True),
    sa.Column('pan_verified', sa.Boolean(), nullable=False),
    sa.Column('pan_verified_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('form_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_udyam_applications_aadhaar_hash'), 'udyam_applications', ['aadhaar_hash'], unique=False)
    op.create_index(op.f('ix_udyam_applications_entrepreneur_name'), 'udyam_applications', ['entrepreneur_name'], unique=False)
    op.create_index(op.f('ix_udyam_applications_pan_hash'), 'udyam_applications', ['pan_hash'], unique=False)
    op.create_index(op.f('ix_udyam_applications_pan_masked'), 'udyam_applications', ['pan_masked'], unique=False)
    op.create_index(op.f('ix_udyam_applications_status'), 'udyam_applications', ['status'], unique=False)
    op.create_table('verification_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.VARCHAR(length=20), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['udyam_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_attempts_app_id'), 'verification_attempts', ['app_id'], unique=False)
    op.create_index(op.f('ix_verification_attempts_kind'), 'verification_attempts', ['kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_attempts_kind'), table_name='verification_attempts')
    op.drop_index(op.f('ix_verification_attempts_app_id'), table_name='verification_attempts')
    op.drop_table('verification_attempts')
    op.drop_index(op.f('ix_udyam_applications_status'), table_name='udyam_applications')
    op.drop_index(op.f('ix_udyam_applications_pan_masked'), table_name='udyam_applications')
    op.drop_index(op.f('ix_udyam_applications_pan_hash'), table_name='udyam_applications')
    op.drop_index(op.f('ix_udyam_applications_entrepreneur_name'), table_name='udyam_applications')
    op.drop_index(op.f('ix_udyam_applications_aadhaar_hash'), table_name='udyam_applications')
    op.drop_table('udyam_applications')
    # ### end Alembic commands ###
